# Generated by Django 5.1.4 on 2025-11-25 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
            options={
                "db_table": "auth_group",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthGroupPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_group_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("codename", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "auth_permission",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_superuser", models.BooleanField()),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=254)),
                ("is_staff", models.BooleanField()),
                ("is_active", models.BooleanField()),
                ("date_joined", models.DateTimeField()),
            ],
            options={
                "db_table": "auth_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserGroups",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_groups",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserUserPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_user_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoAdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_time", models.DateTimeField()),
                ("object_id", models.TextField(blank=True, null=True)),
                ("object_repr", models.CharField(max_length=200)),
                ("action_flag", models.SmallIntegerField()),
                ("change_message", models.TextField()),
            ],
            options={
                "db_table": "django_admin_log",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoContentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_label", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "django_content_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoMigrations",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("app", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("applied", models.DateTimeField()),
            ],
            options={
                "db_table": "django_migrations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoSession",
            fields=[
                (
                    "session_key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("session_data", models.TextField()),
                ("expire_date", models.DateTimeField()),
            ],
            options={
                "db_table": "django_session",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SistemaAsistencia",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("fecha_hora", models.DateTimeField()),
                ("asistio", models.BooleanField()),
            ],
            options={
                "db_table": "sistema_asistencia",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SistemaEvento",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=200)),
                ("fecha", models.DateTimeField()),
                ("lugar", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
            ],
            options={
                "db_table": "sistema_evento",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SistemaMedidor",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("numero_serie", models.CharField(max_length=50, unique=True)),
                ("coordenadas", models.CharField(max_length=100)),
                ("fecha_instalacion", models.DateField()),
            ],
            options={
                "db_table": "sistema_medidor",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SistemaPago",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha_pago", models.DateField()),
                ("estado", models.BooleanField()),
            ],
            options={
                "db_table": "sistema_pago",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SistemaSector",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField()),
                ("estado", models.BooleanField()),
            ],
            options={
                "db_table": "sistema_sector",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SistemaUsuario",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("dni_cedula", models.CharField(max_length=20, unique=True)),
                ("apellido_paterno", models.CharField(max_length=100)),
                (
                    "apellido_materno",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("nombres", models.CharField(max_length=200)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "db_table": "sistema_usuario",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SistemaLectura",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("anio", models.IntegerField()),
                ("mes", models.IntegerField()),
                ("consumo", models.IntegerField()),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="sistema.sistemausuario",
                    ),
                ),
            ],
            options={
                "db_table": "sistema_lectura",
                "managed": True,
                "unique_together": {("usuario", "anio", "mes")},
            },
        ),
    ]
