# Generated by Django 5.2.9 on 2025-12-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sistema", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SistemaTarifa",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tarifa", models.DecimalField(decimal_places=2, max_digits=10)),
                ("activa", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "db_table": "sistema_tarifa",
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="sistemalectura",
            options={"managed": False},
        ),
    ]
